# Generated by Django 5.0.1 on 2024-11-16 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
