# Generated by Django 5.0.1 on 2024-11-16 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0002_package_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='validity',
        ),
        migrations.AddField(
            model_name='package',
            name='date_validity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
