# Generated by Django 5.0.1 on 2024-11-29 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0003_remove_package_validity_package_date_validity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='type',
            field=models.CharField(choices=[('ZNS', 'Đơn giá gửi ZNS'), ('CREATE_OA', 'Tạo zalo OA'), ('CONNECT_OA', 'Kết nối zalo OA'), ('CREATE_WS', 'Tạo wordspace'), ('OA_PREMIUM', 'Nâng cấp OA Premium'), ('MESS', 'Tin nhắn vượt khung'), ('START', 'Phí khởi tạo')], default='ZNS', max_length=255),
        ),
        migrations.AlterField(
            model_name='price',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
