# Generated by Django 5.0.1 on 2024-12-09 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zalo', '0005_userzalo_birthday_userzalo_chatbot_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ZnsComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=60, null=True)),
                ('type', models.CharField(blank=True, choices=[('TITLE', 'Tiêu đề'), ('PARAGRAPH', 'Đoạn văn bản'), ('OTP', 'Mã OTP'), ('TABLE', 'Bảng'), ('LOGO', 'Logo'), ('IMAGES', 'Ảnh'), ('BUTTONS', 'Nút bấm'), ('PAYMENT', 'Thanh toán'), ('VOUCHER', 'Phiếu quà tặng')], max_length=255, null=True)),
                ('layout', models.CharField(blank=True, choices=[('HEADER', 'Phần tiêu đề đầu tin'), ('BODY', 'Nội dung chính'), ('FOOTER', 'Phần cuối tin')], max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'ZnsComponent',
                'db_table': 'zns_component',
            },
        ),
        migrations.CreateModel(
            name='Zns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=60, null=True)),
                ('type', models.IntegerField(choices=[(1, 'ZNS tùy chỉnh'), (2, 'ZNS xác thực'), (3, 'ZNS yêu cầu thanh toán'), (4, 'ZNS voucher'), (5, 'ZNS Đánh giá dịch vụ')], help_text='Loại mẫu tin.')),
                ('tag', models.IntegerField(choices=[(1, 'Transaction'), (2, 'Customer care'), (3, 'Promotion')], help_text='Tag mẫu tin.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_created_zns', to=settings.AUTH_USER_MODEL)),
                ('oa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zalo.zalooa')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_updated_zns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ZNS',
                'verbose_name_plural': 'ZNS',
                'db_table': 'zns',
            },
        ),
        migrations.CreateModel(
            name='ZnsComponentZns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=60, null=True)),
                ('order', models.IntegerField(null=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zns.znscomponent')),
                ('zns', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zns.zns')),
            ],
            options={
                'verbose_name': 'ZnsComponentZns',
                'db_table': 'zns_component_zns',
            },
        ),
        migrations.CreateModel(
            name='ZnsFieldButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button_order', models.IntegerField()),
                ('type', models.IntegerField(choices=[(1, 'Đến trang của doanh nghiệp'), (2, 'Gọi điện'), (3, 'Đến trang thông tin OA'), (4, 'Đến ứng dụng Zalo Mini App của doanh nghiệp'), (5, 'Đến trang tải ứng dụng'), (6, 'Đến trang phân phối sản phẩm'), (7, 'Đến trang web/Zalo Mini App khác'), (8, 'Đến ứng dụng khác')], null=True)),
                ('content', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=30)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zns.znscomponent')),
            ],
            options={
                'verbose_name': 'ZnsFieldButton',
                'db_table': 'zns_field_button',
            },
        ),
        migrations.CreateModel(
            name='ZnsFieldImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zns.znscomponent')),
            ],
            options={
                'verbose_name': 'ZnsFieldImage',
                'db_table': 'zns_field_image',
            },
        ),
        migrations.CreateModel(
            name='ZnsFieldLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('light', models.CharField(max_length=255)),
                ('dark', models.CharField(max_length=255)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zns.znscomponent')),
            ],
            options={
                'verbose_name': 'ZnsFieldLogo',
                'db_table': 'zns_field_logo',
            },
        ),
        migrations.CreateModel(
            name='ZnsFieldOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=10)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zns.znscomponent')),
            ],
            options={
                'verbose_name': 'ZnsFieldOTP',
                'db_table': 'zns_field_otp',
            },
        ),
        migrations.CreateModel(
            name='ZnsFieldParagraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zns.znscomponent')),
            ],
            options={
                'verbose_name': 'ZnsFieldParagraph',
                'db_table': 'zns_field_paragraph',
            },
        ),
        migrations.CreateModel(
            name='ZnsFieldPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_code', models.CharField(max_length=255)),
                ('account_name', models.CharField(max_length=100)),
                ('bank_account', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=12)),
                ('note', models.CharField(max_length=90)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zns.znscomponent')),
            ],
            options={
                'verbose_name': 'ZnsFieldPayment',
                'db_table': 'zns_field_payment',
            },
        ),
        migrations.CreateModel(
            name='ZnsFieldTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_order', models.IntegerField()),
                ('title', models.CharField(max_length=36)),
                ('value', models.CharField(max_length=90)),
                ('row_type', models.IntegerField(choices=[(0, 'Không có hiệu ứng'), (1, 'Thành công'), (2, 'Cập nhật'), (3, 'Lưu ý'), (4, 'Báo lỗi'), (5, 'Cơ bản')], null=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zns.znscomponent')),
            ],
            options={
                'verbose_name': 'ZnsFieldTable',
                'db_table': 'zns_field_table',
            },
        ),
        migrations.CreateModel(
            name='ZnsFieldTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=65)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zns.znscomponent')),
            ],
            options={
                'verbose_name': 'ZnsFieldTitle',
                'db_table': 'zns_field_title',
            },
        ),
        migrations.CreateModel(
            name='ZnsFieldVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('condition', models.CharField(max_length=40)),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(auto_now_add=True)),
                ('voucher_code', models.CharField(max_length=25)),
                ('display_code', models.IntegerField(choices=[(1, 'QR code'), (2, 'Bar code'), (3, 'Text only')], default=1)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zns.znscomponent')),
            ],
            options={
                'verbose_name': 'ZnsFieldVoucher',
                'db_table': 'zns_field_voucher',
            },
        ),
    ]
