# Generated by Django 5.0.1 on 2024-12-09 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
        ('zns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zns',
            name='status',
            field=models.CharField(choices=[(1, 'ZNS tùy chỉnh'), (2, 'ZNS xác thực'), (3, 'ZNS yêu cầu thanh toán'), (4, 'ZNS voucher'), (5, 'ZNS Đánh giá dịch vụ')], default=(1, 'ZNS tùy chỉnh'), max_length=255),
        ),
        migrations.AlterField(
            model_name='znsfieldbutton',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zns.znscomponentzns'),
        ),
        migrations.AlterField(
            model_name='znsfieldimage',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zns.znscomponentzns'),
        ),
        migrations.AlterField(
            model_name='znsfieldlogo',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zns.znscomponentzns'),
        ),
        migrations.AlterField(
            model_name='znsfieldotp',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zns.znscomponentzns'),
        ),
        migrations.AlterField(
            model_name='znsfieldparagraph',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zns.znscomponentzns'),
        ),
        migrations.AlterField(
            model_name='znsfieldpayment',
            name='bank_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.banks'),
        ),
        migrations.AlterField(
            model_name='znsfieldpayment',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zns.znscomponentzns'),
        ),
        migrations.AlterField(
            model_name='znsfieldtable',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zns.znscomponentzns'),
        ),
        migrations.AlterField(
            model_name='znsfieldtitle',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zns.znscomponentzns'),
        ),
        migrations.AlterField(
            model_name='znsfieldvoucher',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zns.znscomponentzns'),
        ),
    ]
