# Generated by Django 5.0.1 on 2024-12-10 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zns', '0002_zns_status_alter_znsfieldbutton_component_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='znsfieldvoucher',
            name='end_date',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='znsfieldvoucher',
            name='start_date',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='ZnsParams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=60, null=True)),
                ('type', models.CharField(choices=[('1', 'Tên khách hàng (30)'), ('2', 'Số điện thoại (15)'), ('3', 'Địa chỉ (200)'), ('4', 'Mã số (30)'), ('5', 'Nhãn tùy chỉnh (30)'), ('6', 'Trạng thái giao dịch (30)'), ('7', 'Thông tin liên hệ (50)'), ('8', 'Giới tính / Danh xưng (5)'), ('9', 'Tên sản phẩm / Thương hiệu (200)'), ('10', 'Số lượng / Số tiền (20)'), ('11', 'Thời gian (20)'), ('12', 'OTP (10)'), ('13', 'URL (200)'), ('14', 'Tiền tệ (VNĐ) (12)'), ('15', 'Bank transfer note (90)')], max_length=10)),
                ('sample_value', models.CharField(blank=True, max_length=200, null=True)),
                ('zns', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zns.zns')),
            ],
            options={
                'verbose_name': 'ZnsParams',
                'db_table': 'zns_params',
            },
        ),
    ]
