# Generated by Django 5.0.1 on 2024-12-11 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zns', '0004_zns_note_alter_zns_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='znsfieldtable',
            name='row_type',
        ),
        migrations.AlterField(
            model_name='zns',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Nháp'), ('PENDING_WZL', 'Chờ duyệt'), ('PENDING_REVIEW', 'Đang duyệt'), ('APPROVED', 'Đã duyệt'), ('REJECTED', 'Đã từ chối'), ('LOCKED', 'Bị khóa')], default='DRAFT', max_length=20),
        ),
        migrations.CreateModel(
            name='ZnsRejectLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reject_date', models.DateField(auto_now_add=True)),
                ('reject_reason', models.TextField(blank=True, null=True)),
                ('zns', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zns.zns')),
            ],
            options={
                'verbose_name': 'ZnsRejectLog',
                'db_table': 'zns_reject_log',
            },
        ),
    ]
