# Generated by Django 5.0.1 on 2024-12-07 02:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0002_alter_customer_options_alter_customerimport_options_and_more'),
        ('tags', '0001_initial'),
        ('zalo', '0005_userzalo_birthday_userzalo_chatbot_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_create_progress', to=settings.AUTH_USER_MODEL)),
                ('oa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='zalo.zalooa')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_update_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progress',
                'db_table': 'progress',
            },
        ),
        migrations.CreateModel(
            name='ProgressTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('BEGIN', 'Bắt đầu'), ('MIDDLE', 'Trung gian'), ('END', 'Kết thúc')], max_length=255, null=True)),
                ('order', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_create_progress_tag', to=settings.AUTH_USER_MODEL)),
                ('oa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='zalo.zalooa')),
                ('progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progress.progress')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_update_progress_tag', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ProgressTag',
                'db_table': 'progress_tag',
            },
        ),
        migrations.CreateModel(
            name='ProgressTagCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_create_progress_tag_customer', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tags.tag')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_update_progress_tag_customer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ProgressTagCustomer',
                'db_table': 'progress_tag_customer',
            },
        ),
        migrations.CreateModel(
            name='ProgressTagCustomerHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(null=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tags.tag')),
            ],
            options={
                'verbose_name': 'ProgressTagCustomerHistory',
                'db_table': 'progress_tag_customer_history',
            },
        ),
        migrations.CreateModel(
            name='ProgressTagUserZalo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_create_progress_tag_user_zalo', to=settings.AUTH_USER_MODEL)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tags.tag')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_update_progress_tag_user_zalo', to=settings.AUTH_USER_MODEL)),
                ('user_zalo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zalo.userzalo')),
            ],
            options={
                'verbose_name': 'ProgressTagUserZalo',
                'db_table': 'progress_tag_user_zalo',
            },
        ),
        migrations.CreateModel(
            name='ProgressTagUserZaloHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(null=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tags.tag')),
                ('user_zalo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zalo.userzalo')),
            ],
            options={
                'verbose_name': 'ProgressTagUserZaloHistory',
                'db_table': 'progress_tag_user_zalo_history',
            },
        ),
    ]
