# Generated by Django 5.0.1 on 2024-12-07 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progresstagcustomer',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progress.progresstag'),
        ),
        migrations.AlterField(
            model_name='progresstagcustomerhistory',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progress.progresstag'),
        ),
        migrations.AlterField(
            model_name='progresstaguserzalo',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progress.progresstag'),
        ),
        migrations.AlterField(
            model_name='progresstaguserzalohistory',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progress.progresstag'),
        ),
    ]
