stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE: wezolo:latest

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build:
  stage: build
  script:
    - docker build -t $DOCKER_IMAGE .
    - docker push $DOCKER_IMAGE

deploy:
  stage: deploy
  environment:
    name: production
  script:
    - ssh user@159.223.60.41 "docker pull $DOCKER_IMAGE"
    - ssh user@159.223.60.41 "docker-compose -f /path/to/docker-compose.yml down"
    - ssh user@159.223.60.41 "docker-compose -f /path/to/docker-compose.yml up -d"
