# Generated by Django 5.0.1 on 2024-12-03 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.CharField(max_length=100, null=True)),
                ('file_name', models.CharField(max_length=255, null=True)),
                ('customer_total', models.IntegerField(null=True)),
                ('customer_success', models.IntegerField(null=True)),
                ('customer_double', models.IntegerField(null=True)),
                ('status', models.CharField(choices=[('IN_PROCESS', 'Đang xử lý'), ('SUCCESS', 'Đã xử lý'), ('ERROR', 'Lỗi')], default='IN_PROCESS', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workspace.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix_name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Nam'), ('Female', 'Nữ')], default='Male', max_length=255, null=True)),
                ('birthday', models.DateField(null=True)),
                ('source', models.IntegerField(null=True)),
                ('note', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workspace.workspace')),
                ('file_import', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.customerimport')),
            ],
        ),
    ]
