# Generated by Django 5.0.1 on 2024-12-09 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('name', models.CharField(max_length=255)),
                ('bin_code', models.CharField(max_length=10)),
                ('short_name', models.CharField(max_length=50)),
                ('logo', models.CharField(blank=True, max_length=200, null=True)),
                ('transfer_supported', models.BooleanField(null=True)),
                ('lookup_supported', models.BooleanField(null=True)),
                ('support', models.IntegerField(null=True)),
                ('is_transfer', models.BooleanField(null=True)),
                ('swift_code', models.CharField(blank=True, max_length=11, null=True)),
            ],
            options={
                'verbose_name': 'Banks',
                'db_table': 'banks',
            },
        ),
    ]
