

class ZaloEventName:
    follow = 'follow'
    user_submit_info = 'user_submit_info'
    un_follow = 'un_follow'
    user_submit_info = 'user_submit_info'
    # TODO: zns
    change_template_status = 'change_template_status'
    # TODO: message
    user_send_text = 'user_send_text'
    user_send_location = 'user_send_location'
    user_send_image = 'user_send_image'
    user_send_link = 'user_send_link'
    user_send_sticker = 'user_send_sticker'
    user_send_gif = 'user_send_gif'
    user_send_audio = 'user_send_audio'
    user_send_video = 'user_send_video'
    user_send_file = 'user_send_file'
    user_send_business_card = 'user_send_business_card'
    user_seen_message = 'user_seen_message'
    oa_send_text = 'oa_send_text'
    oa_send_location = 'oa_send_location'
    oa_send_image = 'oa_send_image'
    oa_send_link = 'oa_send_link'
    oa_send_sticker = 'oa_send_sticker'
    oa_send_gif = 'oa_send_gif'
    oa_send_audio = 'oa_send_audio'
    oa_send_video = 'oa_send_video'
    oa_send_file = 'oa_send_file'
    oa_send_business_card = 'oa_send_business_card'
    oa_seen_message = 'oa_seen_message'
