# Generated by Django 5.0.1 on 2024-12-05 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0002_alter_customer_options_alter_customerimport_options_and_more'),
        ('zalo', '0004_userzalo_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20, null=True)),
                ('color', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_created_tag', to=settings.AUTH_USER_MODEL)),
                ('oa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='zalo.zalooa')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_updated_tag', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TagCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_created_tag_customer', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tags.tag')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_updated_tag_customer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'TagCustomer',
                'db_table': 'tag_customer',
            },
        ),
        migrations.CreateModel(
            name='TagCustomerHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_at', models.DateTimeField(auto_now_add=True)),
                ('type_action', models.CharField(blank=True, choices=[('GAN_TAG', 'Gán Tag'), ('GO_TAG', 'Gỡ Tag')], max_length=255, null=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tags.tag')),
            ],
            options={
                'verbose_name': 'TagCustomerHistory',
                'db_table': 'tag_customer_history',
            },
        ),
        migrations.CreateModel(
            name='TagUserZalo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_created_tag_user_zalo', to=settings.AUTH_USER_MODEL)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tags.tag')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_updated_tag_user_zalo', to=settings.AUTH_USER_MODEL)),
                ('user_zalo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zalo.userzalo')),
            ],
            options={
                'verbose_name': 'TagUserZalo',
                'db_table': 'tag_user_zalo',
            },
        ),
        migrations.CreateModel(
            name='TagUserZaloHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_at', models.DateTimeField(auto_now_add=True)),
                ('type_action', models.CharField(blank=True, choices=[('GAN_TAG', 'Gán Tag'), ('GO_TAG', 'Gỡ Tag')], max_length=255, null=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tags.tag')),
                ('user_zalo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zalo.userzalo')),
            ],
            options={
                'verbose_name': 'TagUserZaloHistory',
                'db_table': 'tag_user_zalo_history',
            },
        ),
    ]
