# Generated by Django 5.0.1 on 2024-12-09 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='color',
        ),
        migrations.AddField(
            model_name='tag',
            name='color_border',
            field=models.CharField(default='ffffff', max_length=255),
        ),
        migrations.AddField(
            model_name='tag',
            name='color_fill',
            field=models.CharField(default='ffffff', max_length=255),
        ),
        migrations.AddField(
            model_name='tag',
            name='color_text',
            field=models.CharField(default='ffffff', max_length=255),
        ),
    ]
