# Generated by Django 5.0.1 on 2024-11-15 09:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0004_alter_sessions_created_at_alter_sessions_login_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_uid', models.UUIDField()),
                ('balance', models.IntegerField(default=0)),
                ('private_key', models.TextField()),
                ('wallet_authorization', models.TextField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wallet',
                'db_table': 'wallet',
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(choices=[('DEPOSIT', 'nạp tiền'), ('EXPENDITURE', 'chi tiêu'), ('RETURN', 'trả lại'), ('PACKAGE', 'mua gói')], default='DEPOSIT', max_length=255)),
                ('method', models.CharField(choices=[('CASH', 'tiền mặt'), ('TRANSFER', 'chuyển khoản')], default='CASH', max_length=255)),
                ('used_at', models.DateTimeField()),
                ('amount', models.IntegerField(default=0)),
                ('bonus_amount', models.IntegerField(default=0)),
                ('total_amount', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'WalletTransaction',
                'db_table': 'wallet_transaction',
            },
        ),
        migrations.CreateModel(
            name='WalletInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('tax_number', models.CharField(default='', max_length=255)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.address')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.wallettransaction')),
            ],
            options={
                'verbose_name': 'WalletInvoice',
                'db_table': 'wallet_invoice',
            },
        ),
    ]
