# Generated by Django 5.0.1 on 2024-11-18 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
