# Generated by Django 5.0.1 on 2024-11-20 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_wallettransaction_oa'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='wallet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wallet.wallet'),
        ),
    ]
