# Generated by Django 5.0.1 on 2024-11-20 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_wallettransaction_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='pay_os_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
