
class PrefKeys:
    WALLET_URL = 'WALLET_URL'
    ENV_DOMAIN = 'ENV_DOMAIN'
    ZALO_APP_SECRET = 'ZALO_APP_SECRET'
    ZALO_OA_ACCESS_TOKEN = 'ZALO_OA_ACCESS_TOKEN'
    ZALO_OA_AUTH_DOMAIN = 'ZALO_OA_AUTH_DOMAIN'
    ZALO_APP_ID = 'ZALO_APP_ID'
    DOMAIN_URL = 'DOMAIN_URL'
