# Generated by Django 5.0.1 on 2024-11-18 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0002_workspacecategory_alter_workspace_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
