# Generated by Django 5.0.1 on 2024-11-29 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('package', '0001_initial'),
        ('reward', '0001_initial'),
        ('wallet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reward',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wallet.wallettransaction'),
        ),
        migrations.AddField(
            model_name='rewardbenefit',
            name='value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='package.price'),
        ),
        migrations.AddField(
            model_name='rewardbenefit',
            name='tier_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reward.rewardtier'),
        ),
    ]
