# Generated by Django 5.0.1 on 2024-11-16 08:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0004_alter_reward_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 15, 8, 17, 50, 257365, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='rewardtier',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
