# Generated by Django 5.0.1 on 2024-11-20 07:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0010_alter_reward_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 19, 7, 1, 36, 73072, tzinfo=datetime.timezone.utc)),
        ),
    ]
