# Generated by Django 5.0.1 on 2024-11-21 04:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0012_alter_reward_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 20, 4, 50, 20, 656923, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='reward',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
