# Generated by Django 5.0.1 on 2024-11-22 07:05

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0003_remove_package_validity_package_date_validity'),
        ('reward', '0014_alter_reward_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 21, 7, 5, 2, 568876, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='rewardbenefit',
            name='value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='package.price'),
        ),
    ]
