# Generated by Django 5.0.1 on 2024-11-28 06:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0019_alter_reward_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 27, 6, 24, 29, 207846, tzinfo=datetime.timezone.utc)),
        ),
    ]
