# Generated by Django 5.0.1 on 2024-11-28 09:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0020_alter_reward_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 27, 9, 38, 29, 274540, tzinfo=datetime.timezone.utc)),
        ),
    ]
