# Generated by Django 5.0.1 on 2024-11-29 04:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0023_alter_reward_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardtier',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reward',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 28, 4, 48, 47, 854656, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='rewardbenefit',
            name='type',
            field=models.CharField(blank=True, choices=[('ZNS', 'Đơn giá gửi ZNS'), ('CREATE_OA', 'Tạo zalo OA'), ('CONNECT_OA', 'Kết nối zalo OA'), ('CREATE_WS', 'Tạo wordspace'), ('OA_PREMIUM', 'Nâng cấp OA Premium'), ('MESS', 'Tin nhắn vượt khung'), ('START', 'Phí khởi tạo')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rewardbenefit',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='rewardtier',
            name='name',
            field=models.CharField(blank=True, choices=[('BRONZE', 'Đồng'), ('SILVER', 'Bạc'), ('GOLD', 'Vàng'), ('PLATINUM', 'Bạch kim')], max_length=255, null=True),
        ),
    ]
