# Generated by Django 5.0.1 on 2024-11-29 04:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0024_rewardtier_code_alter_reward_expiration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 28, 4, 51, 2, 795107, tzinfo=datetime.timezone.utc)),
        ),
    ]
