# Generated by Django 5.0.1 on 2024-11-29 06:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0029_alter_reward_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 28, 6, 20, 36, 205974, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='rewardtier',
            name='min_points',
            field=models.BigIntegerField(default=0),
        ),
    ]
