# Generated by Django 5.0.1 on 2024-11-14 09:50

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('otp', models.CharField(max_length=6)),
                ('status', models.BooleanField(default=False)),
                ('expired_at', models.DateTimeField(default=datetime.datetime(2024, 11, 14, 9, 51, 53, 232916, tzinfo=datetime.timezone.utc))),
            ],
            options={
                'verbose_name': 'Verify',
                'db_table': 'verify',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(default=datetime.datetime(2024, 11, 14, 9, 50, 23, 233349, tzinfo=datetime.timezone.utc))),
                ('logout_time', models.DateTimeField()),
                ('ip_address', models.CharField(max_length=255)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('status', models.CharField(max_length=20)),
                ('token', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(verbose_name=datetime.datetime(2024, 11, 14, 9, 50, 23, 233384, tzinfo=datetime.timezone.utc))),
                ('updated_at', models.DateTimeField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
