# Generated by Django 5.0.1 on 2024-11-15 03:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_verify_alter_user_is_active_sessions'),
    ]

    operations = [
        migrations.AddField(
            model_name='verify',
            name='type',
            field=models.CharField(blank=True, choices=[('REGISTER', 'Đăng ký'), ('FORGOT_PASSWORD', 'Quên mật khẩu')], null=True),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 11, 15, 3, 35, 13, 472886, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 15, 3, 35, 13, 472851, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='verify',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 15, 3, 36, 43, 472486, tzinfo=datetime.timezone.utc)),
        ),
    ]
