# Generated by Django 5.0.1 on 2024-11-16 06:40

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0002_package_code'),
        ('reward', '0002_alter_reward_expiration_date'),
        ('user', '0004_alter_sessions_created_at_alter_sessions_login_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reward.rewardtier'),
        ),
        migrations.AddField(
            model_name='user',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='package.package'),
        ),
        migrations.AddField(
            model_name='user',
            name='package_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='package_start',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 11, 16, 6, 40, 55, 679813, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 16, 6, 40, 55, 679784, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='verify',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 16, 6, 42, 25, 679399, tzinfo=datetime.timezone.utc)),
        ),
    ]
