# Generated by Django 5.0.1 on 2024-11-11 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeVerifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workspace_id', models.IntegerField(default=0)),
                ('code_verifier', models.CharField(blank=True, max_length=255, null=True)),
                ('code_challenge', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExceptionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_message', models.TextField(blank=True, null=True)),
                ('stack_trace', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('oa_id', models.CharField(blank=True, max_length=255, null=True)),
                ('tracking_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FileLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(blank=True, null=True, upload_to='zns/files/')),
            ],
        ),
        migrations.CreateModel(
            name='IPWhitelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('website', models.TextField(blank=True, default='', null=True, verbose_name='Website')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_by', models.IntegerField(choices=[(1, 'Oa'), (2, 'User')], default=2)),
                ('send_at', models.DateTimeField(blank=True, null=True, verbose_name='Sent at')),
                ('user_uid', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('oa_uid', models.CharField(blank=True, max_length=50, null=True)),
                ('message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('tracking_id', models.CharField(blank=True, max_length=255, null=True)),
                ('message_text', models.TextField(blank=True, null=True)),
                ('timestamp', models.FloatField(blank=True, db_index=True, null=True)),
                ('read', models.BooleanField(default=False)),
                ('success', models.BooleanField(default=False)),
                ('use_oa_send', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SendMessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserZalo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('zalo_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='zname')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('user_id', models.CharField(blank=True, max_length=300, null=True, verbose_name='UID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('zalo_img', models.URLField(blank=True, null=True)),
                ('last_message_time', models.DateTimeField(blank=True, null=True)),
                ('user_gender', models.CharField(blank=True, max_length=10, null=True, verbose_name='gender')),
                ('activate', models.BooleanField(default=True)),
                ('oa_id', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ZaloOaLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('in_queue', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ZaloOAMessageQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('oa_id', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('success', models.BooleanField(default=False)),
                ('sent', models.BooleanField(default=False)),
                ('tracking_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ZNSTemplatePurpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ZNSTemplateType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ZNSWebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oa', models.CharField(blank=True, max_length=255, null=True)),
                ('data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('send_by', models.CharField(blank=True, max_length=255, null=True)),
                ('oa_uid', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('msg_id', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zalo.message')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zalo.userzalo'),
        ),
        migrations.CreateModel(
            name='UserZaloTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_id', models.IntegerField(blank=True, null=True)),
                ('user_zalo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zalo.userzalo')),
            ],
        ),
        migrations.CreateModel(
            name='ZaloOA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('secret_app', models.CharField(blank=True, max_length=255, null=True)),
                ('url_callback', models.CharField(blank=True, max_length=255, null=True)),
                ('app_id', models.CharField(blank=True, max_length=255, null=True)),
                ('oa_id', models.CharField(blank=True, max_length=255, null=True)),
                ('oa_name', models.CharField(blank=True, max_length=255, null=True)),
                ('oa_img', models.URLField(blank=True, null=True)),
                ('cate_name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('oa_type', models.IntegerField(default=2)),
                ('num_follower', models.IntegerField(default=0)),
                ('package_name', models.CharField(blank=True, max_length=255, null=True)),
                ('activate', models.BooleanField(default=False)),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('access_token', models.TextField(blank=True, null=True)),
                ('retry', models.IntegerField(blank=True, null=True)),
                ('token_expired_at', models.DateTimeField(blank=True, null=True)),
                ('verify_hook_url', models.CharField(blank=True, max_length=255, null=True)),
                ('verify_html_file', models.FileField(blank=True, null=True, upload_to='zaloa/verify')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zalo_company', to='workspace.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='ZaloMessageQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('retry', models.BooleanField(default=True)),
                ('times', models.IntegerField(default=0)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('sended', models.BooleanField(default=False)),
                ('success', models.BooleanField(default=False)),
                ('message', models.TextField(blank=True, null=True)),
                ('template_id', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.JSONField(blank=True, null=True)),
                ('tracking_id', models.CharField(blank=True, max_length=255, null=True)),
                ('oa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zmq_oa', to='zalo.zalooa')),
            ],
        ),
        migrations.AddField(
            model_name='userzalo',
            name='oa_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zalo.zalooa'),
        ),
        migrations.AddField(
            model_name='message',
            name='oa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zalo.zalooa'),
        ),
        migrations.CreateModel(
            name='ZNSSendLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(blank=True, default=None, null=True)),
                ('res', models.JSONField(blank=True, default=None, null=True)),
                ('template_id', models.CharField(blank=True, max_length=255, null=True)),
                ('mode', models.CharField(blank=True, max_length=255, null=True)),
                ('to', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('oa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zn_send_log', to='zalo.zalooa')),
            ],
        ),
        migrations.CreateModel(
            name='ZNSTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_id', models.CharField(blank=True, max_length=255, null=True)),
                ('template_name', models.CharField(blank=True, max_length=255, null=True)),
                ('variables', models.JSONField(default=dict)),
                ('content', models.TextField(blank=True, null=True)),
                ('type', models.CharField(blank=True, choices=[('confirm_order', 'Confirm Order'), ('send_otp', 'Send Otp'), ('lhe_sent_order', 'Lhe Sent Order'), ('lhe_confirm_order', 'Lhe Confirm Order'), ('lhe_created_order', 'Lhe Created Order')], default='confirm_order', max_length=255, null=True)),
                ('oa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zn_template', to='zalo.zalooa')),
            ],
        ),
        migrations.CreateModel(
            name='ZNSWorkspaceCustom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, max_length=10, null=True)),
                ('zns_status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('cancelled', 'Cancelled'), ('approved', 'Approved')], default='draft', max_length=20)),
                ('template_id', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('preview_url', models.URLField(blank=True, null=True)),
                ('logo_dark', models.ImageField(blank=True, help_text='Upload a dark version of the logo.', null=True, upload_to='zns/logos/', verbose_name='Dark Logo')),
                ('logo_light', models.ImageField(blank=True, help_text='Upload a light version of the logo.', null=True, upload_to='zns/logos/', verbose_name='Light Logo')),
                ('image1', models.ImageField(blank=True, help_text='Upload the first image.', null=True, upload_to='zns/images/', verbose_name='Image 1')),
                ('image2', models.ImageField(blank=True, help_text='Upload the second image.', null=True, upload_to='zns/images/', verbose_name='Image 2')),
                ('image3', models.ImageField(blank=True, help_text='Upload the third image.', null=True, upload_to='zns/images/', verbose_name='Image 3')),
                ('payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('oa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zalo.zalooa')),
                ('purpose', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zalo.znstemplatepurpose')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zalo.znstemplatetype')),
            ],
        ),
        migrations.CreateModel(
            name='ZNSWorkspaceCustomContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('index', models.IntegerField(blank=True, null=True)),
                ('table_content', models.JSONField(blank=True, null=True)),
                ('zns', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zalo.znsworkspacecustom')),
            ],
        ),
    ]
