# Generated by Django 5.0.1 on 2024-11-29 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zalo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zalooa',
            name='sync_status',
            field=models.CharField(choices=[('SYNC', 'Đang đồng bộ'), ('ERROR', 'Ngưng đồng bộ'), ('DONE', 'Đã đồng bộ')], default='SYNC', max_length=255),
        ),
    ]
