# Generated by Django 5.0.1 on 2024-11-22 03:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_alter_sessions_created_at_alter_sessions_login_time_and_more'),
        ('zalo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zalooa',
            name='oa_img',
        ),
        migrations.RemoveField(
            model_name='zalooa',
            name='url_callback',
        ),
        migrations.AddField(
            model_name='zalooa',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='zalooa',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.address'),
        ),
        migrations.AddField(
            model_name='zalooa',
            name='cccd_sau',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zalooa',
            name='cccd_truoc',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zalooa',
            name='chung_minh',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zalooa',
            name='code_ref',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='zalooa',
            name='cong_van',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zalooa',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_create_oa', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='zalooa',
            name='giay_dang_ky',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zalooa',
            name='oa_avatar',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zalooa',
            name='oa_cover',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zalooa',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Chờ đăng ký'), ('REGISTERING', 'Đang đăng ký'), ('NOT_CONNECTED', 'Chưa kết nối'), ('CONNECTED', 'Đã kết nối'), ('DISCONNECTED', 'Ngừng kết nối')], default='PENDING', max_length=255),
        ),
        migrations.AddField(
            model_name='zalooa',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='zalooa',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_update_oa', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='zalooa',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
