# Generated by Django 5.0.1 on 2024-12-03 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zalo', '0002_zalooa_sync_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zalooa',
            old_name='oa_id',
            new_name='uid_zalo_oa',
        ),
    ]
