# Generated by Django 5.0.1 on 2024-11-26 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zalo', '0002_remove_zalooa_oa_img_remove_zalooa_url_callback_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='oa_uid',
        ),
        migrations.RemoveField(
            model_name='message',
            name='read',
        ),
        migrations.RemoveField(
            model_name='message',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='message',
            name='tracking_id',
        ),
        migrations.RemoveField(
            model_name='message',
            name='use_oa_send',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user_uid',
        ),
        migrations.RemoveField(
            model_name='userzalo',
            name='activate',
        ),
        migrations.RemoveField(
            model_name='userzalo',
            name='oa_id',
        ),
        migrations.RemoveField(
            model_name='userzalo',
            name='oa_instance',
        ),
        migrations.RemoveField(
            model_name='userzalo',
            name='user_gender',
        ),
        migrations.RemoveField(
            model_name='userzalo',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='userzalo',
            name='zalo_img',
        ),
        migrations.RemoveField(
            model_name='userzalo',
            name='zalo_name',
        ),
        migrations.AddField(
            model_name='message',
            name='from_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='message_description_photo',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='message_links',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='message_location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='message_thumb',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='message_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='seen',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='message',
            name='src',
            field=models.IntegerField(choices=[(1, 'Oa'), (2, 'User')], default=2),
        ),
        migrations.AddField(
            model_name='message',
            name='time',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='to_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='type_message',
            field=models.CharField(choices=[('TEXT', 'tin nhắn văn bản'), ('VOICE', 'tin nhắn thoại'), ('PHOTO', 'tin nhắn ảnh'), ('GIF', 'tin nhắn GIF'), ('LINK', 'tin nhắn có nội dung là đường link'), ('LINKS', 'tin nhắn theo mẫu đính kèm danh sách'), ('STICKER', 'tin nhắn sticker'), ('LOCATION', 'tin nhắn chia sẻ location')], default='TEXT', max_length=255),
        ),
        migrations.AddField(
            model_name='message',
            name='type_send',
            field=models.CharField(choices=[('USER', 'Người dùng gửi'), ('CAMPAIGN', 'Chiến dịch gửi'), ('BOT', 'Bot gửi')], default='USER', max_length=255),
        ),
        migrations.AddField(
            model_name='userzalo',
            name='avatar_big',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userzalo',
            name='avatar_small',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userzalo',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='gender'),
        ),
        migrations.AddField(
            model_name='userzalo',
            name='is_follower',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userzalo',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='zname'),
        ),
        migrations.AddField(
            model_name='userzalo',
            name='oa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='zalo.zalooa'),
        ),
        migrations.AddField(
            model_name='userzalo',
            name='user_zalo_id',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='UID'),
        ),
        migrations.AddField(
            model_name='zalooa',
            name='ho_chieu',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='oa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='zalo.zalooa'),
        ),
        migrations.AlterField(
            model_name='message',
            name='send_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='send_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zalo.userzalo'),
        ),
    ]
