# Generated by Django 5.0.1 on 2024-11-28 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zalo', '0003_remove_message_oa_uid_remove_message_read_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zalooa',
            name='dev_note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='zalooa',
            name='expiry_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='zalooa',
            name='message_expired',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='zalooa',
            name='message_quota',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='zalooa',
            name='message_remain',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='zalooa',
            name='pause_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='zalooa',
            name='active',
            field=models.CharField(choices=[('ACTIVE', 'Hoạt động'), ('INACTIVE', 'Không hoạt động'), ('EXPIRED', 'Hết hạn gói')], default='ACTIVE', max_length=255, null=True),
        ),
    ]
