# Generated by Django 5.0.1 on 2024-11-28 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zalo', '0004_zalooa_dev_note_zalooa_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zalooa',
            name='package_auto_renew_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='zalooa',
            name='package_valid_through_date',
            field=models.DateField(null=True),
        ),
    ]
