# Generated by Django 5.0.1 on 2024-12-06 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zalo', '0004_userzalo_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='userzalo',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userzalo',
            name='chatbot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userzalo',
            name='message_quota',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userzalo',
            name='message_quota_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userzalo',
            name='message_remain',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userzalo',
            name='prefix_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userzalo',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
